### ISSUE TITLE
Performance

### ISSUE THREAD

**Issue by SwissCommerce** [FriendsOfShopware/FroshPlatformBunnycdnMediaStorage#33]
### Question

Compiling theme for sales channel for : 4606300361c34ae3b69d813bb292f823                                               

 ! [NOTE] Took 402.018354 seconds

This used to take like 100 seconds - when having a deployment with 4-5 plugin updates (that all have css/js) this takes now forever. Is there any way to speed up the process? Currently we are at the point were we probably wont consider it for bigger shops due to the long deployment pipeline.

**Comment by tinect** [comment]
Due to the number of files which got (useless) transferred by shopware, this is normal :-(
Assets (hundreds of svg) f.e. are transferred into several folders. 

Check also the help-text within the config:
![image](https://user-images.githubusercontent.com/135993/197784787-4713e5dd-6689-4929-9981-be46db38d8ca.png)

**Comment by SwissCommerce** [comment]
Yes, I am aware of that. But before a few versions this took 100s (instead of 4s with defaut), but now quadrupled. Thats why I am asking.

**Comment by tinect** [comment]
Can you reproduce it with "before a few versions"?

While this plugin shouldn't affect the time, this could be a part of bunny.net.
But I didn't recognize any relevant increase of api-responses of bunny.

**Comment by SwissCommerce** [comment]
Ok, thx. I guess bunny has to support a better filehandling, otherwise we will have to find a better solution and write our own adapter
