### ISSUE TITLE
Option to sync files + write test file

### ISSUE THREAD

**Issue by Tim-VL** [FriendsOfShopware/FroshPlatformBunnycdnMediaStorage#38]
### Please describe the feature you would like to see implemented.

Hi,

Would it be possible to make an option that sync the files from the host to the cdn storage? 

And would it be an idea to write an test file to the storage so it's visable that the API is working?

Thanks,
Tim

**Comment by tinect** [comment]
Hi Tim

we will not add an option to this plugin for syncing files to the external storage. It should be a different plugin/feature which supports all filesystems like we had in shopware 5. but handling this by PHP is slow and possible to crash due to time limit and so on. I recommend you to use SCP or similar.

there is a test button within the configuration. If you cloned the repository or downloaded source instead of plugin archive, you have to compile the administration on your own.
